const data = {
  products: [
    {
      name: 'Nike Slim shirt',
      slug: 'nike-slim-shirt',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      name: 'Adidas Fit Shirt',
      slug: 'adidas-fit-shirt',
      category: 'Shirts',
      image: '/images/p2.jpg',
      price: 250,
      countInStock: 20,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Nike Slim Pant',
      slug: 'nike-slim-pant',
      category: 'Pants',
      image: '/images/p3.jpg',
      price: 250,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      name: 'Adidas Fit Pant',
      slug: 'adidas-fit-pant',
      category: 'Pants',
      image: '/images/p4.jpg',
      price: 650,
      countInStock: 5,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      //_id: '1',
      name: ' golden top',
      slug: 'golden-top',
      category: 'tops',
      image: '/images/p5.jpg',
      price: 350,
      countInStock: 10,
      brand: 'Toppings',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality top',
    },
    {
      //_id: '6',
      name: 'women-short-dress',
      slug: 'women-short-dress',
      category: 'dreses',
      image: '/images/p6.jpg',
      price: 500,
      countInStock: 40,
      brand: 'dassie',
      rating: 5,
      numReviews: 52,
      description: 'high quality product',
    },
    {
      //_id: '7',
      name: 'casual top',
      slug: 'casual-top',
      category: 'tops',
      image: '/images/p7.jpg',
      price: 350,
      countInStock: 5,
      brand: 'Toppings',
      rating: 4.5,
      numReviews: 72,
      description: 'high quality top',
    },
    {
      //_id: '8',
      name: 'Casual Sleeves',
      slug: 'Casual-Sleeves',
      category: 'tops',
      image: '/images/p8.jpg',
      price: 350,
      countInStock: 10,
      brand: 'Toppings',
      rating: 4.0,
      numReviews: 52,
      description: 'high quality top',
    },
  ],
};
export default data;
